### ISSUE TITLE
切换配色方案时速度好像比较慢

### ISSUE THREAD

**Issue by Justineo** [Ovilia/ECharts-Theme-Builder#11]
建议优化一下体验

**Comment by Ovilia** [comment]
@Justineo 原来从点击主题到展示更新需要 1.5 秒，预加载了预定义主题文件，现在需要 1 秒。几乎都花在 `echarts.setOption` 上了，在第一次调用的时候，需要将近 1 秒，以后调用会由于缓存的关系加速，最快到 0.5 秒——这也是为什么 *debounce* 到了 0.5 秒，也就是说，即使很快地修改参数，最快也需要等0.5 秒更新图表。
总共 14 个图，像关系图和 K 线图处理比较复杂，或者数据比较多，每个图表 `setOption` 的时间在 30 毫秒到 200 毫秒区间，平均 50 毫秒。
暂时我只能想到这里。

**Comment by Justineo** [comment]
其实我从用户角度来看主要问题是我点击以后并不会预期等上 0.5s 才会更新，你给个 loading 或者正在切换之类的提示我觉得就可以接受。有些功能再优化还是有明显的延迟，这个时候你得让用户有预期。不是点了没反应，再试试其他的，发现结果出来了刚才点的那个。

**Comment by pissang** [comment]
可以试下先更新部分，不用一下子全部 setOption
