### ISSUE TITLE
有没有导出的JSON配置文件和实际主题配置项的对应关系？

### ISSUE THREAD

**Issue by hjzheng** [Ovilia/ECharts-Theme-Builder#12]
JSON 文件中配置项，例如 `"datazoomLabelColor": "#999999"` 很难找到 `eCharts` 中对应的配置项。

**Comment by Ovilia** [comment]
参考 https://github.com/Ovilia/ECharts-Theme-Builder/blob/master/app/scripts/main.js#L443
