### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by lundmikkel** [Ovilia/ECharts-Theme-Builder#17]
Is there an English version of the theme builder? My Chinese isn't that good 😄

**Comment by Ovilia** [comment]
@lundmikkel Currently no, but we are planning to translate it later. You may use Google translation for now. Thanks.

**Comment by plainheart** [comment]
Hi @lundmikkel, the English version of the theme builder is now available. Please refer to https://echarts.apache.org/en/theme-builder.html

**Comment by lundmikkel** [comment]
Perfect. Thanks, guys!
