### ISSUE TITLE
下载功能出现报错，不能下载了

### ISSUE THREAD

**Issue by leeviok** [Ovilia/ECharts-Theme-Builder#23]
![4e148cca827cf466176adbec0a0adf8](https://user-images.githubusercontent.com/25154944/89767348-59365b80-db2c-11ea-94f3-e85b7486c392.png)
今天下载主题功能突然不能使用了，上周都还可以的
控制台报错，配置文件没有生成

**Comment by Janwave** [comment]
是的，今天下载主题包都报错
![image](https://user-images.githubusercontent.com/24283750/89776179-f220a300-db3b-11ea-9131-82a605194c2f.png)

**Comment by pissang** [comment]
https://echarts.apache.org/zh/theme-builder.html 已经修复
